addSbtPlugin("com.github.sbt" % "sbt-release"     % "1.3.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"   % "2.0.11")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"        % "2.3.8")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.2")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"  % "1.5.12")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.1.3")
addSbtPlugin("ch.epfl.scala"  % "sbt-tasty-mima"  % "0.5.0")
