addSbtPlugin("com.github.sbt" % "sbt-release"     % "1.1.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"   % "2.0.8")
addSbtPlugin("org.scalameta"  % "sbt-mdoc"        % "2.3.7")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"    % "2.5.1")
addSbtPlugin("com.github.sbt" % "sbt-ci-release"  % "1.5.12")
addSbtPlugin("com.typesafe"   % "sbt-mima-plugin" % "1.1.2")
addSbtPlugin("ch.epfl.scala"  % "sbt-tasty-mima"  % "0.3.1")
