name: Test deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deploy to Github pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn
          cache-dependency-path: ./website/yarn.lock
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        working-directory: ./website
      - name: Test build website
        run: yarn build
        working-directory: ./website
